name: Run Python Tests by Schedule

on:
  schedule:  # Add scheduled trigger
    - cron: "20 20 * * *"    # This will run at 20:20 UTC every day

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3  # Clones your code into the working environment

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.5'  # Specify the Python version you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run flake8
      run: flake8

    - name: Run all tests
      run: pytest -v
